### ISSUE TITLE
duomenų rinkinio pataisimai

### ISSUE THREAD

**Issue by atvirasvilnius** [vilnius/atlieku-tvarkymas#1]
1. atskirti koordinates, nes suplakta į vieną , bei patikrinti, ar nesumaišytas longitude su latitude.
2. prie duomenų rinkinio pridėti įmones kodus.
3. Sumaišytos Konteinerių koordinatės,  pakėlimo vietos koordinatės - teisingos

**Comment by Konteineriai** [comment]
Pakeitimai atlikti.

**Comment by atvirasvilnius** [comment]
Pakeitimai jau įkelti  ar su nauju įkėlimų atsiras? Nes įmonių kodų nematau

**Comment by povilasRi** [comment]
Reiktų dar sutvarkyti koordinačių stulpelių pavadinimus faile - konteineriu_pakelimai.csv, kad nebūtų dviprasmybių ir klaidų paskui

![image](https://user-images.githubusercontent.com/23374638/54201381-2a9af800-44d6-11e9-8a8e-da16ef3f1176.png)

**Comment by atvirasvilnius** [comment]
@Konteineriai ar sutvarekete?

**Comment by Konteineriai** [comment]
Koordinačių stulpelių pavadinimai sutvarkyti.
